[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = true

[programs.localnet]
csvp_protocol = "9kBPnnyFPdoQT68phgSS3QcLNYU4AVeM3A5tGUG8mwrF"
registration = "F9QNYA8Bp36Hg3N79k3C6NNuc98zAUtE1qv9nxMkAN9j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx tests/voting.ts"
